# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ancestors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('is_avatar', models.BooleanField(default=False)),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancestors.Ancestor')),
            ],
        ),
    ]
