# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0003_auto_20171016_1703'),
        ('photos', '0002_auto_20171014_2228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([('ancestor', 'is_avatar')]),
        ),
    ]
