# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20171016_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_avatar',
        ),
    ]
