# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0002_auto_20170625_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancestor',
            name='gender',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='ancestor',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='ancestors.Ancestor'),
        ),
        migrations.AlterUniqueTogether(
            name='ancestor',
            unique_together=set([('first_name', 'last_name', 'birth')]),
        ),
    ]
