# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0003_auto_20171016_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancestor',
            name='abstract',
            field=models.BooleanField(default=True),
        )
    ]
