# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0004_auto_20171016_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestor',
            name='abstract',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ancestor',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ancestor',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ancestor',
            name='third_name',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
    ]
