# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0005_auto_20171019_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancestor',
            name='ancestors',
            field=models.ManyToManyField(blank=True, related_name='_ancestor_ancestors_+', to='ancestors.Ancestor'),
        ),
    ]
