# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestors', '0006_ancestor_ancestors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestor',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
